codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "lib/src/core/error"
  - "lib/src/core/di"
  - "lib/src/core/routes"
  - "api_key.dart"
  - "base_url.dart"
  - "app_widget.dart"
  - "injection.dart"
  - "injection.iconfig.dart"
  - "lib/src/domain/entities"
  - "lib/src/data/models/discover_movies/discover_movie_model.freezed.dart"
  - "lib/src/data/models/discover_movies/movie_result_model.freezed.dart"
  - "lib/src/ui/core"
  - "lib/src/ui/discover_movies/bloc/discover_movie_bloc.freezed.dart"
  - "lib/src/ui/discover_movies/pages"
  - "lib/src/ui/discover_movies/widgets"




