codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "lib/src/core/error"
  - "lib/src/core/di"
  - "lib/src/core/routes"
  - "api_key.dart"
  - "base_url.dart"
  - "app_widget.dart"
  - "injection.dart"
  - "injection.iconfig.dart"
  - "lib/src/domain/entities"
  - "lib/src/ui/core"
  - "lib/src/data/models/discover_movies/discover_movie_model.freezed.dart"
  - "lib/src/data/models/discover_movies/movie_result_model.freezed.dart"
  - "lib/src/ui/discover_movies/bloc/discover_movie_bloc.freezed.dart"
  - "lib/src/ui/discover_movies/pages"
  - "lib/src/ui/discover_movies/widgets"
  - "lib/src/data/models/discover_tv_shows/discover_tv_show_model.freezed.dart"
  - "lib/src/data/models/discover_tv_shows/tv_show_result_model.freezed.dart"
  - "lib/src/ui/discover_tv_shows/bloc/discover_tv_show_bloc.freezed.dart"
  - "lib/src/ui/discover_tv_shows/pages"
  - "lib/src/ui/discover_tv_shows/widgets"
  - "lib/src/data/models/core/backdrops/backdrop_model.freezed.dart"
  - "lib/src/data/models/core/casts/cast_model.freezed.dart"
  - "lib/src/data/models/core/credits/credit_model.freezed.dart"
  - "lib/src/data/models/core/genres/genre_model.freezed.dart"
  - "lib/src/data/models/core/images/image_model.freezed.dart"
  - "lib/src/data/models/core/posters/poster_model.freezed.dart"
  - "lib/src/data/models/core/production_companies/production_company_model.freezed.dart"
  - "lib/src/data/models/core/reviews/review_model.freezed.dart"
  - "lib/src/data/models/core/reviews/review_result_model.freezed.dart"
  - "lib/src/data/models/core/videos/video_model.freezed.dart"
  - "lib/src/data/models/core/videos/video_result_model.freezed.dart"
  - "lib/src/data/models/detail_movies/detail_movie_model.freezed.dart"
  - "lib/src/data/models/detail_movies/production_country_model.freezed.dart"
  - "lib/src/data/models/detail_movies/similar_movie_model.freezed.dart"
  - "lib/src/ui/detail_movies/bloc/detail_movie_bloc.freezed.dart"
